Amazon Credentials:
    accesskey: 
    secretkey: 
    region: us-east-1
    ami_id: ami-013f9768
compute:
    management_server:
        #floating_ip: [FLOATING_IP] #uncomment and provide preallocated ip to disable auto-allocation of new IP on each run
        user_on_management: ubuntu
        userhome_on_management: /home/ubuntu
        instance:
            externally_provisioned: 0
            name: cloudify-management-server
            image_id: ami-013f9768
            instance_type: t1.micro
        management_keypair:
            externally_provisioned: 0
            name: cloudify-management-kp
            #provided:
                #public_key_filepath: [PUBLIC-KEY-PATH]
                #private_key_filepath: [PRIVATE-KEY-PATH]
            auto_generated:
                private_key_target_path: ~/.ssh/cloudify-management-kp.pem
    agent_servers:
        agents_keypair:
            externally_provisioned: 0
            name: cloudify-agents-kp
            #provided:
               #public_key_filepath: [PUBLIC-KEY-PATH]
                #private_key_filepath: [PRIVATE-KEY-PATH]
            auto_generated:
                private_key_target_path: ~/.ssh/cloudify-agents-kp.pem
#networking:
#    agents_security_group:
#            externally_provisioned: 0
#            name: cloudify-sg-agents
#    management_security_group:
#        externally_provisioned: 0
#        name: cloudify-sg-management
#        cidr: 0.0.0.0/0
#
#
#cloudify:
#    cloudify_branch: develop
#    cloudify_components_package_url: https://s3-us-west-1.amazonaws.com/gigaspaces-cosmo-packages/cloudify3-components_3.0.0_amd64.deb
#    cloudify_components_package_url: https://dl.dropboxusercontent.com/u/407576/cloudify3-components_3.0.0_amd64.deb
#    cloudify_package_url: https://s3-us-west-1.amazonaws.com/gigaspaces-cosmo-packages/cloudify3_3.0.0_amd64.deb
#    cloudify_package_url: https://dl.dropboxusercontent.com/u/407576/cloudify3_3.0.0_amd64.deb
#    cloudify_packages_path: /cloudify
#    cloudify_components_package_path: /cloudify3-components
#    cloudify_package_path: /cloudify3
